import type { Metadata } from "next";
import { Geist, Geist_Mono, League_Spartan } from "next/font/google";
import "./globals.css";

const leagueSpartan = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Diogo's Portfolio",
  description: "Generated by create next app",
  // openGraph: {
  //   title: "Diogo Falcão | Mobile Engineer",
  //   description:
  //     "My website portfolio. Mobile engineer specializing in Kotlin, React Native, Flutter.",
  //   url: "https://falcaodiogo.github.io/",
  //   siteName: "Diogo's Portfolio",
  //   images: [
  //     {
  //       url: "/metadata.png",
  //       width: 1200,
  //       height: 630,
  //       alt: "Diogo Falcão Portfolio Preview",
  //     },
  //   ],
  //   type: "website",
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${leagueSpartan.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
